#!/bin/bash -eu

if ! [[ "${USE_NPM-}" = "true" ]]; then
	echo '[medic] skipping npm-init'
	exit 0
fi

npm install -g npm@^5.3.0 grunt-cli --ignore-engines
npm -v
npm install
npm ls || true

npm install grunt-cli -g
npm --prefix shared=libs/phone-number install
node --stack_size=10000 `which grunt` ci-build
