#!/bin/bash -eu

npm install -g npm@^5.3.0
npm -v

if [ ${TEST_SUITE} == "standard" ]; then
	echo '[medic] skipping grunt'
	exit 0
fi

npm install -g grunt-cli
npm install
npm ls || true
node --version
npm --version
cd shared-libs/phone-number && npm install && cd ../..
node --stack_size=10000 `which grunt` ci-build
