#!/bin/bash -eu

if ! [[ "${USE_NPM-}" = "true" ]]; then
	echo '[medic] skipping npm-init'
	exit 0
fi

npm install -g npm@^5.3.0 grunt-cli --ignore-engines
npm -v
npm install
npm ls || true

npm --prefix api install
npm --prefix sentinel install
npm --prefix shared=libs/phone-number install
./node_modules/bin/webdriver-manager update
./node_modules/bin/webdriver-manager start > logs/wedriver.log &
until nc -z localhost 4444; do sleep 1; done

cd shared-libs/phone-number && npm install && cd ../..
node --stack_size=10000 `which grunt` ci-build
